apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  selector: { app: backend }
  ports:
    - name: http
      port: 3000
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
