apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels: { app: backend }
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: {{ if .Values.registry }}{{ printf "%s/%s:%s" .Values.registry .Values.backend.image .Values.backend.tag | quote }}{{ else }}{{ printf "%s:%s" .Values.backend.image .Values.backend.tag | quote }}{{ end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: DB_MODE
              value: {{ .Values.backend.env.DB_MODE | quote }}
            - name: DATABASE_URL
              value: {{ .Values.backend.env.DATABASE_URL | quote }}
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.backend.env.DB_PORT | quote }}
            {{- if .Values.postgres.enabled }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            {{- else }}
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.backend.env.DB_PASSWORD | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
