apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels: { app: frontend }
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: {{ if .Values.registry }}{{ printf "%s/%s:%s" .Values.registry .Values.frontend.image .Values.frontend.tag | quote }}{{ else }}{{ printf "%s:%s" .Values.frontend.image .Values.frontend.tag | quote }}{{ end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
