apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector: { app: frontend }
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
