apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-analytics-service
  namespace: finlab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicas: {{ .Values.analyticsService.hpa.minReplicas }}
  maxReplicas: {{ .Values.analyticsService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.analyticsService.hpa.cpuUtilization }}
